apiVersion: v1
kind: ConfigMap
metadata:
  name: agrius-logstash-pipeline
  labels:
    app: agrius-logstash
data:
  input.conf: |-
    input {
      google_pubsub {
        project_id => "toixotoixo"
        topic => "agrius-india"
        subscription => "agrius-india-logstash"
        json_key_file => "/usr/share/keys/key.json"
        create_subscription => false
      }
    }

  filter.conf: |-
    filter {
      json {
        source => "message"
      }
      date {
        match => [ "created_at", "EEE MMM dd HH:mm:ss '+0000' yyyy"]
      }
      ruby {
        path => '/usr/share/scripts/prep_tweet.rb'
      }
      mutate {
        remove_field => [ "message", "extended_entities", "geo", "host", "favorite_count", "favorited", "place", "coordinates", "source", "filter_level", "contributors", "timestamp_ms", "quoted_status_permalink", "quoted_status_id", "quoted_status_id_str" ]
      }
      if "delete" in [tags] {
        drop {}
      }
    }

  output.conf: |-
    output {
      if "limit" in [tags] {
        elasticsearch {
          hosts => ["agrius-es-elasticsearch-client.default.svc.cluster.local:9200"]
          index => "agrius-limits"
        }
      } else {
        elasticsearch {
          hosts => ["agrius-es-elasticsearch-client.default.svc.cluster.local:9200"]
          document_id => "%{[id]}"
          index => "agrius-%{+xxxx.ww}"
          template => "/usr/share/templates/mapping.json"
        }
      }

    }
